# Generated by Django 5.2.4 on 2026-04-25 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField(help_text='Positive = credit/inflow. Negative = debit/hold. Unit: paise (1 INR = 100 paise).')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('PAYOUT_HOLD', 'Payout Hold'), ('PAYOUT_REFUND', 'Payout Refund')], db_index=True, max_length=20)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, help_text='Optional link to a Payout or external transaction.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.merchant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.merchant')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField(help_text='Amount to disburse in paise. Unit: paise.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.UUIDField(db_index=True, help_text='Client-supplied UUID to prevent duplicate submissions.', unique=True)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of times this payout has been attempted against the bank API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.merchant')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status code of the completed response.', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Serialised JSON response body for replay.', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when a request is being processed; cleared on completion.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='core.merchant')),
            ],
            options={
                'db_table': 'idempotency_records',
                'constraints': [models.UniqueConstraint(fields=('key', 'merchant'), name='unique_idempotency_key_per_merchant')],
            },
        ),
    ]
